// Auto-generated by scripts/set-env.js
export const environment = {
  production: false,
  baseURL: 'https://p2pv1servicesdev-etfrcte5fhdvfrd4.centralindia-01.azurewebsites.net',
  apiEndpoint: 'https://p2pv1servicesdev-etfrcte5fhdvfrd4.centralindia-01.azurewebsites.net',
  storageEncryptionKey: 'perm',
  basicAuthToken: 'Basic cHJvY3VjZXY6cHJvY3VjZXY='
};
