// Auto-generated by scripts/set-env.js
export const environment = {
  production: true,
  baseURL: 'https://quaservicesp.procucev.com',
  apiEndpoint: 'https://quaservicesp.procucev.com',
  storageEncryptionKey: 'perm',
  basicAuthToken: ''
};
