const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const content = fs.readFileSync(filePath, 'utf8');
  const envConfig = {};
  content.split('\n').forEach((line) => {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith('#')) {
      return;
    }
    const eqIdx = trimmedLine.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmedLine.substring(0, eqIdx).trim();
      let val = trimmedLine.substring(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      envConfig[key] = val;
    }
  });
  return envConfig;
}

function resolveEnvConfig(isProdMode) {
  const rootDir = path.resolve(__dirname, '..');

  const envDefault = parseEnvFile(path.join(rootDir, '.env'));
  const envLocal = parseEnvFile(path.join(rootDir, '.env.local'));
  const envProd = parseEnvFile(path.join(rootDir, '.env.prod'));
  const envProdLocal = parseEnvFile(path.join(rootDir, '.env.prod.local'));

  const scopedEnv = isProdMode ? { ...envDefault, ...envProd, ...envProdLocal } : { ...envDefault, ...envLocal };

  const DEFAULT_DEV_URL = 'https://p2pv1servicesdev-etfrcte5fhdvfrd4.centralindia-01.azurewebsites.net';
  const DEFAULT_PROD_URL = 'https://quaservicesp.procucev.com';
  const fallbackUrl = isProdMode ? DEFAULT_PROD_URL : DEFAULT_DEV_URL;

  const backendUrl =
    process.env.BACKEND_URL ||
    process.env.API_ENDPOINT ||
    process.env.API_URL ||
    scopedEnv.BACKEND_URL ||
    scopedEnv.API_ENDPOINT ||
    scopedEnv.API_URL ||
    fallbackUrl;

  const storageEncryptionKey =
    process.env.STORAGE_ENCRYPTION_KEY ||
    scopedEnv.STORAGE_ENCRYPTION_KEY ||
    'perm';

  const basicAuthToken =
    process.env.BASIC_AUTH_TOKEN ||
    scopedEnv.BASIC_AUTH_TOKEN ||
    '';

  const proxyTarget =
    process.env.PROXY_TARGET ||
    scopedEnv.PROXY_TARGET ||
    backendUrl;

  return {
    backendUrl: backendUrl.replace(/\/+$/, ''),
    storageEncryptionKey,
    basicAuthToken,
    proxyTarget: proxyTarget.replace(/\/+$/, '')
  };
}

function setEnvironment() {
  const args = process.argv.slice(2);
  const isProdArg =
    args.includes('--prod') ||
    args.includes('--production') ||
    args.some((a) => a.includes('production') || a.includes('prod'));
  const isProdEnv =
    process.env.NODE_ENV === 'production' ||
    process.env.ENV === 'prod' ||
    process.env.PRODUCTION === 'true';
  const isProd = isProdArg || isProdEnv;

  const devConfig = resolveEnvConfig(false);
  const prodConfig = resolveEnvConfig(true);
  const currentConfig = isProd ? prodConfig : devConfig;

  const envDir = path.resolve(__dirname, '../src/environments');
  if (!fs.existsSync(envDir)) {
    fs.mkdirSync(envDir, { recursive: true });
  }

  const devEnvFileContent = `// Auto-generated by scripts/set-env.js
export const environment = {
  production: false,
  baseURL: ${JSON.stringify(devConfig.backendUrl)},
  apiEndpoint: ${JSON.stringify(devConfig.backendUrl)},
  storageEncryptionKey: ${JSON.stringify(devConfig.storageEncryptionKey)},
  basicAuthToken: ${JSON.stringify(devConfig.basicAuthToken)}
};
`;

  const prodEnvFileContent = `// Auto-generated by scripts/set-env.js
export const environment = {
  production: true,
  baseURL: ${JSON.stringify(prodConfig.backendUrl)},
  apiEndpoint: ${JSON.stringify(prodConfig.backendUrl)},
  storageEncryptionKey: ${JSON.stringify(prodConfig.storageEncryptionKey)},
  basicAuthToken: ${JSON.stringify(prodConfig.basicAuthToken)}
};
`;

  const devFilePath = path.join(envDir, 'environment.ts');
  const prodFilePath = path.join(envDir, 'environment.prod.ts');

  fs.writeFileSync(devFilePath, devEnvFileContent, 'utf8');
  fs.writeFileSync(prodFilePath, prodEnvFileContent, 'utf8');

  // Update proxy.config.json
  const proxyPath = path.resolve(__dirname, '../proxy.config.json');
  const proxyConfig = {
    '/oauth': {
      target: currentConfig.proxyTarget,
      secure: false,
      logLevel: 'debug',
      changeOrigin: true
    }
  };
  fs.writeFileSync(proxyPath, JSON.stringify(proxyConfig, null, 2) + '\n', 'utf8');

  console.log(`[set-env] Active Mode: ${isProd ? 'production' : 'development'}`);
  console.log(`[set-env] Backend URL (Dev) -> ${devConfig.backendUrl}`);
  console.log(`[set-env] Backend URL (Prod) -> ${prodConfig.backendUrl}`);
}

setEnvironment();
